In [2]:
import numpy as np

# 假设 x 是一个 n x m 的二维数组
x = np.array([i for i in range(120)]).reshape(4,30)  # 4行30列的数组

print("原始数组形状:", x.shape)
print(x)

# 将二维数组每5列分成一组，转为三维数组
# 先将 x 的维度重塑为 (n, m//4, 5)，然后转置以使分组为第一维度
new_array = x.reshape(x.shape[0], -1, 5).transpose(1, 0, 2)

print("\n新的三维数组形状:", new_array.shape)
print(new_array)


原始数组形状: (4, 30)
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
   48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
  108 109 110 111 112 113 114 115 116 117 118 119]]

新的三维数组形状: (6, 4, 5)
[[[  0   1   2   3   4]
  [ 30  31  32  33  34]
  [ 60  61  62  63  64]
  [ 90  91  92  93  94]]

 [[  5   6   7   8   9]
  [ 35  36  37  38  39]
  [ 65  66  67  68  69]
  [ 95  96  97  98  99]]

 [[ 10  11  12  13  14]
  [ 40  41  42  43  44]
  [ 70  71  72  73  74]
  [100 101 102 103 104]]

 [[ 15  16  17  18  19]
  [ 45  46  47  48  49]
  [ 75  76  77  78  79]
  [105 106 107 108 109]]

 [[ 20  21  22  23  24]
  [ 50  51  52  53  54]
  [ 80  81  82  83  84

In [2]:
import json
import requests

subscriptionKey = "eb2a854dfec240a2a21f168ab96a57f4"
customConfigId = "c8a6c10f-37a3-4264-b310-d26f9bc6c43f"
searchTerm = "microsoft"
url = 'https://api.bing.microsoft.com/v7.0/custom/search?' + 'q=' + searchTerm + '&' + 'customconfig=' + customConfigId
r = requests.get(url, headers={'Ocp-Apim-Subscription-Key': subscriptionKey})
print(r.text)
response_json = r.json()
print(response_json)

{"_type": "SearchResponse", "instrumentation": {"_type": "ResponseInstrumentation", "pingUrlBase": "https:\/\/www.bingapis.com\/api\/ping?IG=D8853BDC5D654AA4A202013A39553890&CID=38E45A6F99B1686122584F4D98FD6932&ID=", "pageLoadPingUrl": "https:\/\/www.bingapis.com\/api\/ping\/pageload?IG=D8853BDC5D654AA4A202013A39553890&CID=38E45A6F99B1686122584F4D98FD6932&Type=Event.CPT&DATA=0"}, "queryContext": {"originalQuery": "microsoft"}, "webPages": {"webSearchUrl": "https:\/\/www.bing.com\/search?q=microsoft", "webSearchUrlPingSuffix": "DevEx,5703.1", "totalEstimatedMatches": 28200000, "value": [{"id": "https:\/\/api.bing.microsoft.com\/api\/v7\/#WebPages.0", "name": "Microsoft——AI、云、生产力、计算、游戏和应用", "url": "https:\/\/www.microsoft.com\/zh-cn\/", "urlPingSuffix": "DevEx,5121.1", "datePublished": "2021-06-22T14:20:56.0000000", "datePublishedDisplayText": "2021年6月22日", "isFamilyFriendly": true, "displayUrl": "https:\/\/www.microsoft.com\/zh-cn", "snippet": "浏览适合家庭或企业的 Microsoft 产品、服务和支持。购买 Microsoft

In [1]:
import torch

# 检查 CUDA 是否可用
if torch.cuda.is_available():
    print("CUDA is available!")
    print(f"CUDA version: {torch.version.cuda}")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    print(f"Current GPU: {torch.cuda.current_device()} - {torch.cuda.get_device_name(torch.cuda.current_device())}")
else:
    print("CUDA is not available.")


CUDA is available!
CUDA version: 12.4
Number of GPUs: 1
Current GPU: 0 - NVIDIA GeForce RTX 4090
